### ISSUE TITLE
Identify new Features to be Added to the Repository

### ISSUE THREAD

**Issue by waradis6509650088** [Kanchanop6509650229/CS360-QWERTYUIOP#9]
**วัตถุประสงค์**: 
- เสนอและตกลง Feature ใหม่ที่จะเพิ่มเข้าไปใน project และเพิ่ม Feature ที่จะทำเข้าไปใน project backlog

**Task**:
- [x] เลือก Feature ที่จะเพิ่มไปในโปรเจค 
- [ ] สร้าง Issue ใหม่ตามฟีเจอร์ที่เลือกและเพิ่มลงไปใน Project backlog

**Features to be added**: 
- User Profiles and Registration 
- Write new blog
- Add new restaurant
- Search for relevant terms in blog posts
- Tell distance with google map
- Support Thai language
- Support chat
- Tell the restaurant‘s signature menu
- Rating system
- follow the blogger
- Personalized Recommendations
- User Reviews and Comments

**Comment by Kanchanop6509650229** [comment]
- User Profiles and Registration[+Login]
- Write new blog
- Add new restaurant

**Comment by waradis6509650088** [comment]
- accept search terms from user to search for relevant terms in blog posts shown on screen

**Comment by Haritch-6509650757** [comment]
- Tell distance with google map
- Support thai language
- Support chat

**Comment by Primchawat1** [comment]
- tell the restaurant’ s signature menu
- rate the blog

**Comment by Primchawat1** [comment]
- follow the blogger

**Comment by Thantawan6509650427** [comment]
- Personalized Recommendations
- User Reviews and Comments
